services : 
  db : # Service de base de données MySQL
    image :  mysql:8.0
    restart : always
    container_name :  MySQL 
    ports : 
      - "3306:3306" 
    environment : 
      - MYSQL_ROOT_PASSWORD=dispatcher1234
      - MYSQL_DATABASE=printer_db
    volumes : 
      -  db_data:/var/lib/mysql

  phpmyadmin: # Service phpMyAdmin pour gérer la base de données MySQL [OPTIONNEL]
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  portainerServer: # Service Portainer pour la gestion de Docker
    image: portainer/portainer-ce:latest
    container_name: portainer_server
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes: # Volumes pour persister les données de MySQL et Portainer
  db_data:
  portainer_data: