services : 
  db : 
    image :  mysql:8.0
    container_name :  MySQL 
    ports : 
      - "3306:3306" 
    environment : 
      - MYSQL_ROOT_PASSWORD=dispatcherRoot1234
      - MYSQL_USER=dispatcher
      - MYSQL_PASSWORD=dispatcherRoot1234
      - MYSQL_DATABASE=printer_db
    volumes : 
      -  db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  portainerServer:
    image: portainer/portainer-ce:latest
    container_name: portainer_server
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  db_data:
  portainer_data: